FROM anapsix/alpine-java

RUN adduser -D {{user}} -h /home/{{user}} -u {{uid}}

USER {{user}}:{{user}}

WORKDIR /home/{{user}}

RUN mkdir HentaiAtHome

WORKDIR /home/{{user}}/HentaiAtHome

ADD --chown={{user}} HentaiAtHome.jar ./

ENTRYPOINT ["java", "-jar", "HentaiAtHome.jar"]
